name: Feature
description: Add a feature request
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: [""]
body:
  - type: checkboxes
    id: read-guidelines
    attributes:
      label: Contributor Guidelines
      description: Please confirm that you have read the [Contributor Guidelines and Discussion](https://github.com/reactplay/react-kolkata/discussions/35) before submitting this feature request.
      options:
        - label: I have read the guidelines and discussion
          required: true

  - type: markdown
    attributes:
      value: |
        Please provide the feature request details in the fields below.
        Ensure that your request is clear and concise to help us understand the need for this feature.
  - type: textarea
    id: feature-details
    attributes:
      label: Feature Details
      description: Describe the feature in detail and explain the problem it solves.
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: If you have a solution in mind, please describe it here.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
